---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.nameSpace }}
spec: 
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
  selector:
    role: frontend